version: "3.9"

services:
  db:
    image: postgres:15
    container_name: codevault-postgres
    restart: always
    environment:
      POSTGRES_USER: codevault
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: codevaultdb
    ports:
      - "5432:5432"
    volumes:
      - codevault_data:/var/lib/postgresql/data

  app:
    image: cwlumm/codevault-app:latest
    container_name: codevault-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/codevaultdb
      SPRING_DATASOURCE_USERNAME: codevault
      SPRING_DATASOURCE_PASSWORD: secret123
    ports:
      - "8080:8080"

volumes:
  codevault_data:
