server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codevaultdb
    username: codevault
    password: secret123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate        # or 'update' during local development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: cm8zM3pOb1dUUDNWNjhNclloZzNrdVRGeXVOelhRdndFRDFxYTlNTHlsaDdqVHptOU96R2JHMXorU2dJSkk1dw==
    ttlMinutes: 60
